# Generated by Django 2.2.5 on 2022-11-29 23:05

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(upload_to='clube', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('imagem', stdimage.models.StdImageField(upload_to='jogador', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogador',
            },
        ),
        migrations.CreateModel(
            name='PosicaoSetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca.PosicaoSetor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
            },
        ),
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca.Clube', verbose_name='Clube')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca.Jogador', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexão',
            },
        ),
        migrations.CreateModel(
            name='Busca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca.Categoria', verbose_name='Categoria')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca.Clube', verbose_name='Clube')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca.Posicao', verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
    ]
