# Generated by Django 2.2.5 on 2022-12-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busca',
            options={'verbose_name': 'Busca', 'verbose_name_plural': 'Buscas'},
        ),
    ]
