# Generated by Django 2.2.5 on 2022-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0002_auto_20221201_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='cor',
            field=models.CharField(default='#fff', max_length=10, verbose_name='Cor'),
        ),
    ]
