# Generated by Django 2.2.5 on 2022-12-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0003_clube_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='descricao',
            field=models.TextField(default='', max_length=500, verbose_name='Descrição'),
        ),
    ]
