# Generated by Django 3.1.4 on 2022-12-12 04:00

import busca.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0004_jogador_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=busca.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=busca.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
    ]
