# Generated by Django 3.1.4 on 2022-12-13 05:38

import busca.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0005_auto_20221212_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=busca.models.get_file_path, variations={'thumb': {'crop': True, 'height': 350, 'width': 350}}, verbose_name='Imagem'),
        ),
    ]
