# Generated by Django 2.2.5 on 2022-12-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0006_auto_20221213_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='email',
            field=models.CharField(default='', max_length=150, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
        ),
    ]
